spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5433/company_details
spring.datasource.username=postgres
spring.datasource.password=Smarakpatro.4
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema="schema 1"